timezone: "Europe/Madrid"

WeatherData:
  # service: "Meteocat"
  # api_key_name: "meteocat"
  # weather_station : "UK"
  service: "AEMET"
  api_key_name: "AEMET"
  weather_station : "0076"

Logger:
  level: "DEBUG"
  filename: "debug.log"
  format: "%(asctime)s %(levelname)s %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"