timezone: "Europe/Madrid"

WeatherData:
  service: "Meteocat"
  api_key_name: "meteocat"
  weather_station : "UK"

Logger:
  level: "DEBUG"
  filename: "debug.log"
  format: "%(asctime)s %(levelname)s %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"